# Koneksi ke Bigquery

In [ ]:
from google.colab import auth
from google.cloud import bigquery

In [ ]:
auth.authenticate_user()
PROJECT_ID = "my-project-2602-505412"
client = bigquery.Client(project=PROJECT_ID)
print("Connected:", PROJECT_ID)

Connected: my-project-2602-505412

#Cek Tabel TheLook E-commerce

In [ ]:

query = '''
SELECT table_name
FROM `bigquery-public-data.thelook_ecommerce.INFORMATION_SCHEMA.TABLES`
ORDER BY table_name
'''
client.query(query).to_dataframe()

             table_name
0  distribution_centers
1                events
2       inventory_items
3           order_items
4                orders
5              products
6                 users

#Case Study

Tampilkan seluruh tabel order!

In [ ]:
query_1 = '''
SELECT *
FROM `bigquery-public-data.thelook_ecommerce.orders`
'''
client.query(query_1).to_dataframe()

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item
0,30,28,Cancelled,F,2026-06-01 11:14:10+00:00,NaT,NaT,NaT,1
1,32,30,Cancelled,F,2025-06-15 09:08:43+00:00,NaT,NaT,NaT,1
2,65,56,Cancelled,F,2025-02-20 08:23:48+00:00,NaT,NaT,NaT,3
3,94,83,Cancelled,F,2025-11-24 12:38:01+00:00,NaT,NaT,NaT,3
4,109,95,Cancelled,F,2024-07-17 14:04:48+00:00,NaT,NaT,NaT,1
...,...,...,...,...,...,...,...,...,...
124716,124702,99980,Shipped,M,2026-01-25 09:31:39+00:00,NaT,2026-01-26 12:33:39+00:00,NaT,1
124717,124708,99985,Shipped,M,2026-07-23 19:09:55+00:00,NaT,2026-07-24 13:30:55+00:00,NaT,1
124718,124709,99986,Shipped,M,2026-02-15 04:04:07+00:00,NaT,2026-02-15 21:18:07+00:00,NaT,1
124719,124710,99987,Shipped,M,2024-08-24 13:06:12+00:00,NaT,2024-08-25 12:18:12+00:00,NaT,1
124720,124718,99998,Shipped,M,2026-07-15 23:37:36+00:00,NaT,2026-07-16 06:30:36+00:00,NaT,1

In [ ]:
df_orders = client.query(query_1).to_dataframe()

In [ ]:
df_orders.head ()

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item
0,30,28,Cancelled,F,2026-06-01 11:14:10+00:00,NaT,NaT,NaT,1
1,32,30,Cancelled,F,2025-06-15 09:08:43+00:00,NaT,NaT,NaT,1
2,65,56,Cancelled,F,2025-02-20 08:23:48+00:00,NaT,NaT,NaT,3
3,94,83,Cancelled,F,2025-11-24 12:38:01+00:00,NaT,NaT,NaT,3
4,109,95,Cancelled,F,2024-07-17 14:04:48+00:00,NaT,NaT,NaT,1

#Exploratory Data Analyst

In [ ]:
df_orders.shape

(124721, 9)

In [ ]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124721 entries, 0 to 124720
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      124721 non-null  Int64
 1   user_id       124721 non-null  Int64
 2   status        124721 non-null  object
 3   gender        124721 non-null  object
 4   created_at    124721 non-null  datetime64[us, UTC]
 5   returned_at   12376 non-null   datetime64[us, UTC]
 6   shipped_at    81061 non-null   datetime64[us, UTC]
 7   delivered_at  43528 non-null   datetime64[us, UTC]
 8   num_of_item   124721 non-null  Int64
dtypes: Int64(3), datetime64[us, UTC](4), object(2)
memory usage: 8.9+ MB

#Filter

Hanya tampilkan status Complete

In [ ]:
df_orders_filtered = df_orders[df_orders['status'] == 'Complete']

In [ ]:
df_orders_filtered.head()

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item
9240,10,6,Complete,F,2026-07-31 11:21:33+00:00,NaT,2026-07-31 23:47:33+00:00,2026-08-05 15:13:33+00:00,2
9241,11,7,Complete,F,2024-11-02 03:54:34+00:00,NaT,2024-11-04 15:54:34+00:00,2024-11-08 17:44:34+00:00,1
9242,16,13,Complete,F,2024-04-18 21:54:35+00:00,NaT,2024-04-21 09:37:35+00:00,2024-04-23 19:12:35+00:00,1
9243,19,16,Complete,F,2023-07-04 21:03:15+00:00,NaT,2023-07-06 11:47:15+00:00,2023-07-08 18:47:15+00:00,2
9244,23,20,Complete,F,2026-04-18 23:09:53+00:00,NaT,2026-04-19 19:28:53+00:00,2026-04-23 08:05:53+00:00,1

#TASK!

# Buat tabel df_users dimana tabel memuat kolom:
Country,
gender,
total user

Kalau tabel df_users sudah muncul. buatlah filter gender hanya yang Female

In [ ]:
from google.colab import auth
from google.cloud import bigquery

In [ ]:
auth.authenticate_user()
PROJECT_ID = "my-project-2602-505412"
client = bigquery.Client(project=PROJECT_ID)
print("Connected:", PROJECT_ID)

Connected: my-project-2602-505412

In [ ]:
query_2 = '''
SELECT *
FROM `bigquery-public-data.thelook_ecommerce.users`
'''
client.query(query_2).to_dataframe()

,id,first_name,last_name,email,age,gender,state,street_address,postal_code,city,country,latitude,longitude,traffic_source,created_at,user_geom
0,60622,Jeffrey,Herrera,jeffreyherrera@example.com,69,M,Acre,016 Whitaker Port Apt. 407,69980-000,null,Brasil,-8.065346,-72.870949,Search,2022-01-03 09:53:00+00:00,POINT(-72.87094866 -8.065346116)
1,13500,Timothy,Stanley,timothystanley@example.net,59,M,Acre,17603 Christopher Radial,69980-000,null,Brasil,-8.065346,-72.870949,Email,2024-03-05 13:26:00+00:00,POINT(-72.87094866 -8.065346116)
2,22694,Charlotte,Williams,charlottewilliams@example.org,63,F,Acre,4935 Barker Fords Suite 244,69980-000,null,Brasil,-8.065346,-72.870949,Search,2020-07-19 10:56:00+00:00,POINT(-72.87094866 -8.065346116)
3,77067,Andrew,Flores,andrewflores@example.com,58,M,Acre,63982 Frank Fall Suite 965,69980-000,null,Brasil,-8.065346,-72.870949,Organic,2025-06-09 07:26:00+00:00,POINT(-72.87094866 -8.065346116)
4,87343,George,Miles,georgemiles@example.org,70,M,Acre,1534 Stewart Crest Apt. 371,69980-000,null,Brasil,-8.065346,-72.870949,Search,2019-08-31 11:44:00+00:00,POINT(-72.87094866 -8.065346116)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,24913,David,Davis,daviddavis@example.net,57,M,Île-de-France,122 Wilson Route Apt. 523,77320,Choisy-en-Brie,France,48.763993,3.319993,Search,2025-06-12 15:31:00+00:00,POINT(3.31999321 48.76399331)
99996,81058,Melinda,Soto,melindasoto@example.com,16,F,Île-de-France,150 Brandon Valley Apt. 555,77320,Choisy-en-Brie,France,48.763993,3.319993,Search,2024-01-06 04:25:00+00:00,POINT(3.31999321 48.76399331)
99997,8747,Samuel,Figueroa,samuelfigueroa@example.com,12,M,Île-de-France,0463 David Summit Apt. 777,77320,Choisy-en-Brie,France,48.763993,3.319993,Search,2020-10-02 10:06:00+00:00,POINT(3.31999321 48.76399331)
99998,85671,Mitchell,Keith,mitchellkeith@example.net,55,M,Île-de-France,2679 Frederick Square Suite 678,77320,Choisy-en-Brie,France,48.763993,3.319993,Search,2022-06-25 10:13:00+00:00,POINT(3.31999321 48.76399331)
99999,23341,John,Peters,johnpeters@example.org,19,M,Île-de-France,735 Ross Harbor Suite 831,77320,Choisy-en-Brie,France,48.763993,3.319993,Search,2019-05-12 09:08:00+00:00,POINT(3.31999321 48.76399331)

In [ ]:
df_users = client.query(query_2).to_dataframe()

In [ ]:
df_users.head()

,id,first_name,last_name,email,age,gender,state,street_address,postal_code,city,country,latitude,longitude,traffic_source,created_at,user_geom
0,60622,Jeffrey,Herrera,jeffreyherrera@example.com,69,M,Acre,016 Whitaker Port Apt. 407,69980-000,null,Brasil,-8.065346,-72.870949,Search,2022-01-03 09:53:00+00:00,POINT(-72.87094866 -8.065346116)
1,13500,Timothy,Stanley,timothystanley@example.net,59,M,Acre,17603 Christopher Radial,69980-000,null,Brasil,-8.065346,-72.870949,Email,2024-03-05 13:26:00+00:00,POINT(-72.87094866 -8.065346116)
2,22694,Charlotte,Williams,charlottewilliams@example.org,63,F,Acre,4935 Barker Fords Suite 244,69980-000,null,Brasil,-8.065346,-72.870949,Search,2020-07-19 10:56:00+00:00,POINT(-72.87094866 -8.065346116)
3,77067,Andrew,Flores,andrewflores@example.com,58,M,Acre,63982 Frank Fall Suite 965,69980-000,null,Brasil,-8.065346,-72.870949,Organic,2025-06-09 07:26:00+00:00,POINT(-72.87094866 -8.065346116)
4,87343,George,Miles,georgemiles@example.org,70,M,Acre,1534 Stewart Crest Apt. 371,69980-000,null,Brasil,-8.065346,-72.870949,Search,2019-08-31 11:44:00+00:00,POINT(-72.87094866 -8.065346116)

In [ ]:
df_users.groupby(['country', 'gender'])['id'].count()

country         gender
Australia       F          1040
                M          1099
Austria         F             1
                M             2
Belgium         F           628
                M           591
Brasil          F          7357
                M          7230
China           F         16923
                M         17057
Colombia        F             4
                M             7
España          F             1
                M             1
France          F          2293
                M          2338
Germany         F          2071
                M          2117
Japan           F          1210
                M          1119
Poland          F           102
                M           122
South Korea     F          2718
                M          2718
Spain           F          1956
                M          1955
United Kingdom  F          2324
                M          2396
United States   F         11293
                M         11327
Name: id, dtype: Int64

In [ ]:
df_users_filtered = df_users[df_users['gender'] == 'F']

In [ ]:
df_users_filtered.head()

,id,first_name,last_name,email,age,gender,state,street_address,postal_code,city,country,latitude,longitude,traffic_source,created_at,user_geom
2,22694,Charlotte,Williams,charlottewilliams@example.org,63,F,Acre,4935 Barker Fords Suite 244,69980-000,null,Brasil,-8.065346,-72.870949,Search,2020-07-19 10:56:00+00:00,POINT(-72.87094866 -8.065346116)
5,45900,Whitney,Russell,whitneyrussell@example.net,47,F,Acre,10986 John Walks Suite 371,69980-000,null,Brasil,-8.065346,-72.870949,Email,2022-02-26 07:07:00+00:00,POINT(-72.87094866 -8.065346116)
6,424,Natasha,Moore,natashamoore@example.net,14,F,Acre,1651 Jessica Club Apt. 809,69980-000,null,Brasil,-8.065346,-72.870949,Organic,2022-12-15 18:48:00+00:00,POINT(-72.87094866 -8.065346116)
13,25126,Deborah,Mcdaniel,deborahmcdaniel@example.org,21,F,Acre,1722 Ayers Drive,69980-000,null,Brasil,-8.065346,-72.870949,Search,2021-11-17 08:01:00+00:00,POINT(-72.87094866 -8.065346116)
14,26316,Kathryn,Arias,kathrynarias@example.net,42,F,Acre,1852 Gilbert Keys Apt. 960,69980-000,null,Brasil,-8.065346,-72.870949,Search,2024-05-15 13:04:00+00:00,POINT(-72.87094866 -8.065346116)